# Generated by Django 3.1.5 on 2021-01-09 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_auto_20210108_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='manufacturers_categories',
            field=models.ForeignKey(blank=True, db_column='manufacturers_categories', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sklep.manufacturerscategories'),
        ),
        migrations.AlterModelTable(
            name='products',
            table='product',
        ),
    ]
